spring:
  redis:
#    数据库索引（默认为0）
    database: 0
#    服务器地址
    host: 192.168.2.40
#    服务器连接端口
    port: 6379
#    服务器连接密码（默认为空）
    password: qsmy0424
    lettuce:
      pool:
#        连接池最大连接数（使用负值表示没有限制） 默认为8
        max-active: 8
#        连接池最大阻塞等待时间（使用负值表示没有限制）  默认为-1
        max-wait: -1
#        连接池的最大空闲连接  默认为8
        max-idle: 8
#        连接池的最小空闲连接  默认为0
        min-idle: 0